# Mosquitto TLS listener
listener 8883
cafile /Users/rahul/Documents/Projects/Intrusion Detection System/Certs/ca.crt
certfile /Users/rahul/Documents/Projects/Intrusion Detection System/Certs/server.crt
keyfile /Users/rahul/Documents/Projects/Intrusion Detection System/Certs/server.key
require_certificate false
tls_version tlsv1.2

# Logging
log_dest file /Users/rahul/Documents/Projects/Intrusion Detection System/IDS_core/mosquitto.log

log_type all

connection_messages true
allow_anonymous true
